### ISSUE TITLE
Is there an actual repository that I can clone to make my own images

### ISSUE THREAD

**Issue by vochong** [damianperera/openwrt-rpi#2]
Hello,

Do you have an actual repository that I can clone to my own images, since I may need to use lots of kmod packages for which I need to build images locally.   Thanks a lot.

**Comment by wulfy23** [comment]
Apologies for the late reply. If you are modding kernel sources or other similar low level code then rolling your own from official (OpenWrt) sources is the way to go...

If you are just adding bone stock kmods then;

a-1) if they are required for boot (network~internet / disk) then you could just slipstream official ones into an image similar to how damian creates this image
a-2) if not just install them afterwards and my build will/~should~ take care of installing them next time you upgrade or whatever
b) seek input from my repo regarding the kmods you need and whether they can just be added for everyone or similar conditional is possible within the build
c) devise another creative or tangential pathway...
