### ISSUE TITLE
Discussion: how does this differ from

### ISSUE THREAD

**Issue by jeff47** [damianperera/openwrt-rpi#3]
**Is your feature request related to a problem? Please describe.**

Where does this fit in the overall ecosystem?  How is it different from vanilla openwrt or wulfy?

**Comment by damianperera** [comment]
It's for personal use so I can reformat my RPI with the latest version and the configurations I use the most. You are welcome to fork the repository and add the configurations you use as well and get scheduled builds with updates, similar to what others have done 🙂
