### ISSUE TITLE
Old kernel does not exist anymore

### ISSUE THREAD

**Issue by Malmis** [damianperera/openwrt-rpi#4]
Can not run opkg update anymore because of the kernel doesn't exist anymore.

Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2711/kmods/6.1.32-1-6dbbbe5f721a07182c581131feeef2b3/Packages.gz, wget returned 8.

Oldest kernel available is 6.1.42-1-2788142dedb58f01c99eafa3de2a5300 and newest is 6.1.62-1-15f046bfc7c597e53342c144a339bd58

**Comment by wulfy23** [comment]
uploaded for you(s) to; http://github.com/wulfy23/rpi4-opkg/blob/master/kmods/6.1.32-1-6dbbbe5f721a07182c581131feeef2b3

update your /etc/opkg/customfeeds.conf (or distfeeds.conf) to the path above
(luci > system > software > configure opkg)
